# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '^$'
fail_fast: false
repos:

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-install
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args:
          - --without
          - dev
          - -f
          - requirements.txt
          - -o
          - ./requirements/prod.txt

  -  repo: https://github.com/astral-sh/ruff-pre-commit
     # Ruff version.
     rev: v0.3.7
     hooks:
       # Run the linter.
       - id: ruff
         args: [--config, pyproject.toml, --fix]
       # Run the formatter.
       - id: ruff-format
         args: [--config, pyproject.toml]

  -  repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v3.2.0
     hooks:
     -   id: check-added-large-files
     -   id: check-case-conflict
     -   id: check-docstring-first
     -   id: check-json
     -   id: check-toml
     -   id: check-yaml
     -   id: detect-private-key
     -   id: end-of-file-fixer
     -   id: name-tests-test
     -   id: pretty-format-json
     -   id: requirements-txt-fixer
     -   id: trailing-whitespace

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: poetry run pytest -m 'not webtest'
      language: system
      types: [python]
      pass_filenames: false
      always_run: false
