[pytest]
log_level = DEBUG
log_file_format = %(asctime)s %(levelname)-8s (%(filename)s:%(lineno)s) [%(name)s %(module)s %(funcName)s] %(message)s
log_file_date_format = %Y-%m-%dT%H:%M:%S.%f %z
log_file_mode = a
log_file = logs/tests.log

log_cli = true
log_cli_level = WARNING
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%dT%H:%M:%S

addopts = --doctest-modules --strict-markers --cov=incolume -sx --cov-report term-missing --cov-report html:coverage_report/html --cov-report xml:coverage_report/cov.xml

env =
    GIT_AUTHOR_NAME=test
    GIT_COMMITTER_NAME=test
    GIT_AUTHOR_EMAIL=test@incolume.com.br
    GIT_COMMITTER_EMAIL=test@incolume.com.br
    GIT_ALLOW_PROTOCOL=file
    VIRTUALENV_NO_DOWNLOAD=1
    PRE_COMMIT_NO_CONCURRENCY=1

required_plugins = pytest-mock pytest-cov pytest-timeout pytest-env

testpaths =
  tests

python_functions = test_*

python_classes =
  Case*
  TestCase*
  Test*

python_files =
  tests.py
  test_*.py
  *_test.py
  check_*.py
  *_check.py

markers =
  ; marks tests as slow (deselect with '-m "not slow"')
  slow
  ; marks tests as fast (deselect with '-m \"not fast\"')",
  fast
  ; marks tests as fast (deselect with '-m \"not offci\"')",
  offci
  ; marks tests as webtest (deselect with '-m \"not webtest\"')",
  webtest

filterwarnings =
    ; ignore::DeprecationWarning
