import pytest
from dojo import dna_complementary



@pytest.mark.parametrize(
    ['entrance', 'expected'],
    (
        ("ATTGC", "TAACG"),
        ("GTAT", "CATA"),
        ('TTGGGGGGCGTCAGCTGCTAAGTTGAATATCTTAGAAGTGGTTTATTAGA', 'AACCCCCCGCAGTCGACGATTCAACTTATAGAATCTTCACCAAATAATCT'),
        ('GTATGAGGCTGGATTTGCCGACACCTTCTGCCCCCATAGGCTGTATGGGG', 'CATACTCCGACCTAAACGGCTGTGGAAGACGGGGGTATCCGACATACCCC'),
        ('AGGCAGATACGTCGCGACCATTGTACAAGAATCACTTCACACGGTCTGGA', 'TCCGTCTATGCAGCGCTGGTAACATGTTCTTAGTGAAGTGTGCCAGACCT'),
        ('GATGTCCTGATCTCTACAGTATCGACATGGGTAACCCACCCATGTAAAGG', 'CTACAGGACTAGAGATGTCATAGCTGTACCCATTGGGTGGGTACATTTCC'),
        ('CTAACTCATACACGTACGATGCTGGAGGGATGAATAGCGCGGGCACGTTC', 'GATTGAGTATGTGCATGCTACGACCTCCCTACTTATCGCGCCCGTGCAAG'),
        ('TACCGAGCTCCCTACGCTTGCATCGACAGGACCACGTACGATCCGAGGTC', 'ATGGCTCGAGGGATGCGAACGTAGCTGTCCTGGTGCATGCTAGGCTCCAG'),
        ('CTTATCGTAAGCGGTTACGCCACAGATGTTCTACCTTATCTCTCATTCAC', 'GAATAGCATTCGCCAATGCGGTGTCTACAAGATGGAATAGAGAGTAAGTG'),
        ('CCACGTCCGAATCCAATCCTTATGCGCTTTTTCACAGTTGCATAGGTCTA', 'GGTGCAGGCTTAGGTTAGGAATACGCGAAAAAGTGTCAACGTATCCAGAT'),
        ('GGACGTGTGCGCCGAGAGGCTCGAGGGCGTTAGTCTTGTACCTAGGGGGC', 'CCTGCACACGCGGCTCTCCGAGCTCCCGCAATCAGAACATGGATCCCCCG'),
        ('GCCTTCACGGGTGAAGTATTGTTCCGGGCACGGATAATGACAGTGCTGAG', 'CGGAAGTGCCCACTTCATAACAAGGCCCGTGCCTATTACTGTCACGACTC'),
        ('TAACCCTTGGTCGGAGCAAGCTCTGAGTCACAACATGGCATTACCTTGCG', 'ATTGGGAACCAGCCTCGTTCGAGACTCAGTGTTGTACCGTAATGGAACGC'),

    )
)
def test_dna_complementary(entrance, expected):
    assert dna_complementary(entrance) == expected
