# This is a basic workflow to help you get started with Actions

name: Docs Generator by CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    #tags:
    # - "*.*.*"
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Setup python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Install dependencies from pack
      - name: Install dependencies
        run: |
          python -m pip install -U poetry
          poetry install

      # Runs a single command using the runners shell
      - name: Show poetry version
        run: poetry -V

      # Generate and deploy the documentation

      - name: Update CHANGELOG.md
        run: |
          git fetch
          git tag -d Unreleased
          poetry run gcl -r -u https://github.com/incolume-jedi/coding-dojo/compare docs/about/CHANGELOG.md

      - name: Generate and deploy the documentation
        run: |
          git pull origin --no-rebase
          poetry run mkdocs gh-deploy --config-file mkdocs.yml --remote-branch webdoc
